### ISSUE TITLE
Reunião geral: 6 fev. 2023

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#37]
# Reunião Geral, 06 de fevereiro de 2023

- Data: 06/02/2023
- Participantes:
  - Elis Lages @elislages
  - Fabio Bispo @fabiobj
  - Debora Oliveira @deboraos
  - Mari Bedran @maribedran
  - Juliana Barros @tiidadavena
  - Ana Cecília Vieira @cecivieira
  - Patricia Silva @patriciasilvarecife
  - Carine Neris @carine-neris

## Ata

- Orçamentos de almoço para o evento
- Fabio enviou mensagem para O GDG para encontrar espaço (local do evento) 
- Nova proposta de identidade visual #30
- Prazo para avaliação final da nova proposta da identidade visual: 10/02
- Redirecionar orçamento de comida para buffet (almoço)

### Ações para serem realizadas

- [ ] Criar repositório do site (copiar do evento 2022 e tirar animações) (@elislages, @tiidadavena, @tiidadavena) #41
- [ ] Programação estrutura (1 e 2 trilhas) (@cecivieira, @elislages, @deboraos, @maribedran ) quinta a noite (a partir das 20h) #42
- [ ] Buscar orçamentos de locais pagos (falar com Lorena) #40
